### ISSUE TITLE
[meta] Improve testing

### ISSUE THREAD

**Issue by benbender** [kiebitz-oss/vanellus-inoeg#12]
This library is intended to run in the browser, but we are running tests in node. This might hide bugs and subtle errors. Additionally a more mature testing-approach would be nice and therefor a reproducible testing-scenario is needed. To achieve this, we should mock getRandomValues to have reproduceable outputs which might be snapshotted. 

- [x] Move from mocha to jest
- [x] Setup jsdom with polyfills or similar for the webcrypto-api to have a browser-env for testing
- [ ] [Mock getRandomValues()](https://stackoverflow.com/questions/63484075/mock-window-crypto-getrandomvalues-in-jest) in tests for reproduceable tests
- [x] Move polyfills into a test-setup
- [x] Snapshot-testing for api-output?
- [x] Have more granular tests for api-results
- [x] Check for additional conditions inside bigger integration-tests with assertations
- [x] More granular unit-tests for low-level methods
- [ ] ...
